version: "3.8"

services:
  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: organica
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql  # init SQL

  backend:
    image: prashant6749/organica-backend:${TAG}
    container_name: organica-backend
    ports:
      - "9090:9090"
    environment:
      - DB_URL=jdbc:mysql://db:3306/organica
      - DB_USERNAME=admin
      - DB_PASSWORD=12345678
    depends_on:
      - db
    restart: always

  frontend:
    image: prashant6749/organica-frontend:${TAG}
    container_name: organica-frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_BACKEND_URL=http://<EC2_PUBLIC_IP>:9090
    depends_on:
      - backend
    restart: always

volumes:
  mysql_data:
